### ISSUE TITLE
Not working with Rails 4.1

### ISSUE THREAD

**Issue by nglx** [attr-encrypted/attr_encrypted#105]
Throwing:

```
attr_encrypted.rb:258:in `method_missing': undefined local variable or method `generated_feature_methods'
```
