### ISSUE TITLE
`attr_encrypted?` method removed?

### ISSUE THREAD

**Issue by connorshea** [attr-encrypted/attr_encrypted#198]
Was `attr_encrypted?` removed in 2.0.0? It's not documented anywhere that it was, as far as I can tell. This is preventing us from using 2.0.0 in devise-two-factor. It worked fine in 1.4.0. Is there a good replacement for it?

[Specific commit for `devise-two-factor` that runs into this problem](https://github.com/connorshea/devise-two-factor/tree/23100036e95921cc115f330a01ef16e154bd3a06). Here's the [specific line](https://github.com/connorshea/devise-two-factor/blob/23100036e95921cc115f330a01ef16e154bd3a06/lib/devise_two_factor/models/two_factor_authenticatable.rb#L12) where it's being used, and here's the error I'm getting:
```
Connors-MacBook-Pro:devise-two-factor connor$ bundle exec rake
/Users/connor/.rvm/rubies/ruby-2.3.0/bin/ruby -I/Users/connor/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib:/Users/connor/.rvm/gems/ruby-2.3.0/gems/rspec-support-3.4.1/lib /Users/connor/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/exe/rspec spec/devise/models/two_factor_authenticatable_spec.rb spec/devise/models/two_factor_backupable_spec.rb
/Users/connor/Programming/devise-two-factor/lib/devise_two_factor/models/two_factor_authenticatable.rb:12:in `block in <module:TwoFactorAuthenticatable>': undefined method `attr_encrypted?' for TwoFactorAuthenticatableDouble:Class (NoMethodError)
```

**Comment by saghaulor** [comment]
No it wasn't removed. 

https://github.com/attr-encrypted/attr_encrypted/blob/2.0.0/lib/attr_encrypted.rb#L216

**Comment by connorshea** [comment]
Apologies, must be an error on our side then.
